[build]
  command = "ng build --configuration production"
  publish = "dist/pwa-app/browser"

[[plugins]]
  package = "@netlify/angular-runtime"
  
[[redirects]]
  from = "/*"
  to = "/index.csr.html"
  status = 200